def render_pdf_header(pdf, final_json):
    customer = final_json.get("customer", {})
    policy = final_json.get("policy", {})
    metadata = final_json.get("metadata", {})

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Underwriting Report", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Generated By: {metadata.get('generatedBy', '')}", ln=True)
    pdf.cell(0, 6, f"Timestamp: {metadata.get('timestamp', '')}", ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Customer Information", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Name: {customer.get('firstName', '')} {customer.get('lastName', '')}", ln=True)
    pdf.cell(0, 6, f"DOB: {customer.get('dob', '')}", ln=True)
    pdf.cell(0, 6, f"State: {customer.get('state', '')}", ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Policy Information", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, f"Product Type: {policy.get('productType', '')}", ln=True)
    pdf.cell(0, 6, f"Coverage Amount: {policy.get('requestedCoverageAmount', '')}", ln=True)
    pdf.cell(0, 6, f"Term: {policy.get('requestedTerm', '')}", ln=True)
    pdf.cell(0, 6, f"Effective Date: {policy.get('effectiveDate', '')}", ln=True)

    pdf.ln(10)
